spring:
  application:
    name: movie-battle
  datasource:
    username: sa
    url: jdbc:h2:mem:movie-battle
    driverClassName: org.h2.Driver
    password: password
  h2:
    console:
      enabled: 'true'
      path: /h2-console
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

server:
  port: 5000
  servlet:
    context-path: /${spring.application.name}/v1